variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - publish

compile:
  when: manual
  only:
    - ci_test
  stage: build
  tags:
    - bsg
  script:
    - ./configure --with-arch=rv64ima --with-abi=lp64 --with-cmodel=medany --prefix=`(pwd)`/target
    - make -j ${CI_NUM_CORES} > compile.log
    - make install 

publish:
  when: manual
  stage: publish
  tags:
    - bsg
  script:
    - echo "Doing release of ${RELEASE_TAG}"
